spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  # ...
  # Step 1a: End of SSL configuration
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1dUNU5TTVdXaTBSM01TNHEKWm02Y3M3L3ltaVNaZDRIUTBzNFBqM2NSVFZhaFJBTkNBQVJURTIreTJXN1NRd2c4akR2V2dWSjJRVzhyOTdEWgpQK1NZeXdYOFB6MDRyTnBhWlZycGUrellkWWY2bXlER2JhMStDQTU0MjIyZnUraHl3Qyt2Nnd0ZgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPekNDQWVHZ0F3SUJBZ0lSQUlUcGN1ZlBscWJMTzZ3VmJuZEVZSUV3Q2dZSUtvWkl6ajBFQXdJd2dZRXgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURXJNQ2tHQTFVRUN3d2lZVzUwYUc5dQplVUJoYm5Sb2IyNTVMVlJvYVc1clVHRmtJQ2hCYm5Sb2IyNTVLVEV5TURBR0ExVUVBd3dwYld0alpYSjBJR0Z1CmRHaHZibmxBWVc1MGFHOXVlUzFVYUdsdWExQmhaQ0FvUVc1MGFHOXVlU2t3SGhjTk1qWXdOREUxTVRJeU5qSTMKV2hjTk1qZ3dOekUxTVRJeU5qSTNXakJXTVNjd0pRWURWUVFLRXg1dGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZwpZMlZ5ZEdsbWFXTmhkR1V4S3pBcEJnTlZCQXNNSW1GdWRHaHZibmxBWVc1MGFHOXVlUzFVYUdsdWExQmhaQ0FvClFXNTBhRzl1ZVNrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVEUyK3kyVzdTUXdnOGpEdlcKZ1ZKMlFXOHI5N0RaUCtTWXl3WDhQejA0ck5wYVpWcnBlK3pZZFlmNm15REdiYTErQ0E1NDIyMmZ1K2h5d0Mrdgo2d3RmbzJRd1lqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdId1lEClZSMGpCQmd3Rm9BVUMzcWVXdEUwTDZiL0xsUThnYlgxOC8xY3FiMHdHZ1lEVlIwUkJCTXdFWUlQYkc5allXd3UKTUhoa1ltVXVaR1YyTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUVPczRydXNqUkI2S3M3ODlMejg0QktrcklMRwpqWHJubGRrOFp5YlpnWTYyQWlFQTRKZFU3TnE4d3pyUWNhTHJWTHMxZ3l0NXVodDgrUnVlbi9pcXhXR2YrSTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTRENDQWUyZ0F3SUJBZ0lRV3NtQTIrUEtpZ2lYZExZMU82NGtKakFLQmdncWhrak9QUVFEQWpDQmdURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1Tc3dLUVlEVlFRTERDSmhiblJvYjI1NQpRR0Z1ZEdodmJua3RWR2hwYm10UVlXUWdLRUZ1ZEdodmJua3BNVEl3TUFZRFZRUUREQ2x0YTJObGNuUWdZVzUwCmFHOXVlVUJoYm5Sb2IyNTVMVlJvYVc1clVHRmtJQ2hCYm5Sb2IyNTVLVEFlRncweU5qQTBNVFV4TWpJMk1qZGEKRncwek5qQTBNVFV4TWpJMk1qZGFNSUdCTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZwpRMEV4S3pBcEJnTlZCQXNNSW1GdWRHaHZibmxBWVc1MGFHOXVlUzFVYUdsdWExQmhaQ0FvUVc1MGFHOXVlU2t4Ck1qQXdCZ05WQkFNTUtXMXJZMlZ5ZENCaGJuUm9iMjU1UUdGdWRHaHZibmt0VkdocGJtdFFZV1FnS0VGdWRHaHYKYm5rcE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXl1dTBGQ2hSR25SY3A2N0MraVk2UVBnUAo0MFlPR2NWamkvSTdMMUMxQ20zcENrWW9MTFg0WTdUc2FKbkp4eTVnaTMzWjU4M1pndFBVamlLVmx4MGc1S05GCk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUUKRkF0Nm5sclJOQyttL3k1VVBJRzE5ZlA5WEttOU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRDFiUWRnVDdHcApoWFliYytETmdBT1ZUelN5TmRPK1dsaWIrb1dnY2I0Qlh3SWhBSnVUWHBYZjBGdGNZcUtaenl6VUNKV3hpSVhsCkdCQk1lWnFueFlCOFdXbncKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
server:
  port: 8443
  ssl:
    enabled: true
  # Step 1b: Enable SSL and specify ssl bundle
  # ...
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  # Step 5: End of session cookie configuration